name: learn-github-actions
on:
  push:
    # branches:
    #   - master
    # * includes all files , ** includes all files and directories
    paths:
      - "dev/backend/cloud/**"
      - "dev/backend/*"
      - "dev/frontend/**"
    # paths-ignore:
    #   - "dev/backend/logs.txt"
    #   - ".github/**"
  # workflow_dispatch:                                                              // add button to manual trigger

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello otherchanges World"
        shell: bash
