name: learn-github-actions
on:
  push:
    # branches:
    #   - master
    paths:
      - "dev/backend/monitor/**"
      - "dev/backend/costing/*"
    # paths-ignore:
    #   - "dev/backend/logs.txt"
    #   - ".github/**"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello otherchanges World"
        shell: bash
